name: dictation_studio_flutter
description: "A Flutter project for dictation studio channel and video management."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # HTTP client for API calls
  http: ^1.1.0

  # State management
  provider: ^6.1.1

  # Network image caching
  cached_network_image: ^3.3.0

  # Navigation and routing
  go_router: ^12.1.3

  # JSON serialization
  json_annotation: ^4.8.1

  # UI components
  flutter_staggered_grid_view: ^0.7.0

  # Loading animations
  flutter_spinkit: ^5.2.0

  # Progress indicators
  percent_indicator: ^4.2.3

  # Material Design icons
  material_design_icons_flutter: ^7.0.7296

  # Authentication and backend
  supabase_flutter: ^2.5.6
  google_sign_in: ^6.2.1

  # Encryption and security
  crypto: ^3.0.3

  # Local storage
  shared_preferences: ^2.2.2

  # URL launcher for OAuth
  url_launcher: ^6.3.2
  app_links: ^6.3.2
  dart_jsonwebtoken: ^3.2.0

  # Logging framework
  logging: ^1.2.0

  # Date formatting
  intl: ^0.19.0

  # YouTube player for video playback
  youtube_player_flutter: ^9.0.3
  
  # Fallback video player 
  video_player: ^2.8.2
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # JSON code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Add fonts if needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
